runtime: custom
env: flex

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 3
  disk_size_gb: 10

readiness_check:
  path: "/api/health"
  check_interval_sec: 650
  timeout_sec: 600
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 2700
