runtime: custom
env: flex

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

readiness_check:
  path: "/api/health"
  check_interval_sec: 5
  timeout_sec: 5
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 600

beta_settings:
  cloud_sql_instances: divine-turbine-261911:us-central1:metabase-app-db=tcp:5432

env_variables:
  MB_DB_DBNAME: 'metabase-db'
  MB_DB_TYPE: 'postgres'
  MB_DB_HOST: '34.59.231.4'
  MB_DB_PORT: '5432'
  MB_DB_USER: 'metabase-user'
  MB_DB_PASS: 'huroqu10'
  MB_JETTY_PORT: '8080'
